### ISSUE TITLE
Create new database structure

### ISSUE THREAD

**Issue by pavelzaichyk** [varkhipov/Reader#18]
![](https://camo.githubusercontent.com/64b1d933a22ad3c19f2ea0ae2c828e9004dc1327/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f36353639343437312f64622f7265616465722d736368656d612d322e706e67)

New db schema - https://github.com/varkhipov/Reader/wiki/Database
Create scripts - https://dl.dropboxusercontent.com/u/65694471/db/Reader_sqlite_create.sql
Drop scripts - https://dl.dropboxusercontent.com/u/65694471/db/Reader_sqlite_drop.sql

**Comment by varkhipov** [comment]
Add schedule versions support

**Comment by pavelzaichyk** [comment]
update database structure
new schema https://dl.dropboxusercontent.com/u/65694471/db/reader-schema-4.png
